### ISSUE TITLE
Image Resizing not working.

### ISSUE THREAD

**Issue by peatsn** [OpenNebula/addon-drbdmanage#8]
If i deploy a new VM with changed Imagessize it will not be reconized by DRBD.The Volume stay's in the same Size. Resizing by hand with drbdmanage resize-volume does not work ether.
Is resizing not supported with DRBD Storage backend ?

**Comment by JOJ0** [comment]
Hi,
that's correct, currently on-the-fly image-resize is not supported by addon-drbdmanage, but with the folowing procedure it is possible to create a DRBD-backed VM with a specific disk size (inside VM steps are for Linux VMs, please adjust for your OS):

* instantiate VM with desired disksize (it won't resize it correctly but at least it writes the correct size to the VM-definition template (check with “onevm show”)
* drbdmanage resize-volume OpenNebula-image……
* virsh blockresize ….
* inside the vm:
    * kpartx /dev/vda
    * fdisk /dev/vda # delete partition vda1 and recreate it using all available space
    * reboot
    * resize2fs /dev/vda1

Hope that helps
Jojo

**Comment by peatsn** [comment]
Sorry for the late answer and thanks for your's. We moved to lizardfs , because DRBD was very unreliable and slow in my use case.

Many Thanks
