### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by Snowmanko** [OpenNebula/addon-drbdmanage#9]
Hi,
there is currently limitation mentioned in readme : snapshots of images are not available
I just want to know if there will be some patch so snapshots will be available.

Thanks,

Martin

**Comment by haySwim** [comment]
This is due to a restriction in drbdmanage, which is lower down in the stack from this driver.

Afaik, this isn't a pressing issue for that project right now, but once that's resolved we can implement live snapshotting actions here.
